name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # <--- Измените, если ваша основная ветка называется не main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ВАШ_ID_ПРОЕКТА }}' # СЮДА НУЖНО ВСТАВИТЬ ИМЯ ВАШЕГО ПРОЕКТА
          channelId: live
          projectId: lnd-reise
          expires: 30d
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.1//01i_J7mJICbluCgYIARAAGAESNwF-L9IrjL4PMznJ7InEie7hXEK6tY9HdKho3gpYWlP_fOfG24ev3M-tX0iScf1KzXPIC1QcYNQ }} 
