name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # <--- Измените, если ваша основная ветка называется не main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Если ваш сайт требует сборки (React, Vue, и т.д.), раскомментируйте этот блок:
      #- name: Setup Node.js
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: '20' 

      #- name: Install dependencies
      #  run: npm install 

      #- name: Build
      #  run: npm run build # <--- Используйте вашу команду сборки

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ВАШ_ID_ПРОЕКТА }}' # СЮДА НУЖНО ВСТАВИТЬ ИМЯ ВАШЕГО ПРОЕКТА
          channelId: live
          projectId: ВАШ_ID_ПРОЕКТА # <--- ЕЩЕ РАЗ ВСТАВЬТЕ ID ВАШЕГО ПРОЕКТА
          expires: 30d
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Токен, который мы добавили на Шаге 3
